version: "3.9"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run --token ${TOKEN}
    volumes:
      - ./tunnel:/etc/cloudflared
networks:
  default:
    name: tunnel
    driver: bridge


